name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag clearlinux-dnf
    - name: Test
      run: docker run --rm clearlinux-dnf dnf repolist -v
